START TRANSACTION;

-- 한글 포함이므로 세션 캐릭터셋이 맞는지 확인 필요
-- SET NAMES utf8mb4;

INSERT INTO `tag` (`name`, `category`, `sub_category`, `status`)
VALUES
    ('LLM', 'AI', 'Generative AI', 'ACTIVE'),
    ('ChatGPT', 'AI', 'Generative AI', 'ACTIVE'),
    ('StableDiffusion', 'AI', 'Generative AI', 'ACTIVE'),
    ('Midjourney', 'AI', 'Generative AI', 'ACTIVE'),
    ('GenerativeAI', 'AI', 'Generative AI', 'ACTIVE'),
    ('TensorFlow', 'AI', '머신러닝/딥러닝', 'ACTIVE'),
    ('PyTorch', 'AI', '머신러닝/딥러닝', 'ACTIVE'),
    ('Keras', 'AI', '머신러닝/딥러닝', 'ACTIVE'),
    ('MachineLearning', 'AI', '머신러닝/딥러닝', 'ACTIVE'),
    ('DeepLearning', 'AI', '머신러닝/딥러닝', 'ACTIVE'),
    ('Python', 'AI', '언어/데이터', 'ACTIVE'),
    ('데이터분석', 'AI', '언어/데이터', 'ACTIVE'),
    ('DataScience', 'AI', '언어/데이터', 'ACTIVE'),
    ('NLP', 'AI', '언어/데이터', 'ACTIVE'),
    ('R', 'AI', '언어/데이터', 'ACTIVE'),
    ('MLOps', 'AI', '운영 및 응용', 'ACTIVE'),
    ('AI윤리', 'AI', '운영 및 응용', 'ACTIVE'),
    ('컴퓨터비전', 'AI', '운영 및 응용', 'ACTIVE'),
    ('자율주행', 'AI', '운영 및 응용', 'ACTIVE'),
    ('React', '개발', '프론트엔드', 'ACTIVE'),
    ('VueJS', '개발', '프론트엔드', 'ACTIVE'),
    ('Angular', '개발', '프론트엔드', 'ACTIVE'),
    ('NextJS', '개발', '프론트엔드', 'ACTIVE'),
    ('TypeScript', '개발', '프론트엔드', 'ACTIVE'),
    ('JavaScript', '개발', '프론트엔드', 'ACTIVE'),
    ('NodeJS', '개발', '백엔드', 'ACTIVE'),
    ('Spring', '개발', '백엔드', 'ACTIVE'),
    ('Django', '개발', '백엔드', 'ACTIVE'),
    ('GoLang', '개발', '백엔드', 'ACTIVE'),
    ('Java', '개발', '백엔드', 'ACTIVE'),
    ('Python*', '개발', '백엔드', 'ACTIVE'),
    ('Docker', '개발', 'DevOps & Infra', 'ACTIVE'),
    ('Kubernates', '개발', 'DevOps & Infra', 'ACTIVE'),
    ('AWS', '개발', 'DevOps & Infra', 'ACTIVE'),
    ('Azure', '개발', 'DevOps & Infra', 'ACTIVE'),
    ('GCP', '개발', 'DevOps & Infra', 'ACTIVE'),
    ('Cloud', '개발', 'DevOps & Infra', 'ACTIVE'),
    ('SQL', '개발', '데이터베이스', 'ACTIVE'),
    ('NoSQL', '개발', '데이터베이스', 'ACTIVE'),
    ('MySQL', '개발', '데이터베이스', 'ACTIVE'),
    ('MongoDB', '개발', '데이터베이스', 'ACTIVE'),
    ('Redis', '개발', '데이터베이스', 'ACTIVE'),
    ('Git', '개발', '기타', 'ACTIVE'),
    ('Testing', '개발', '기타', 'ACTIVE'),
    ('Security', '개발', '기타', 'ACTIVE'),
    ('Microservice', '개발', '기타', 'ACTIVE'),
    ('MSA', '개발', '기타', 'ACTIVE'),
    ('Figma', '디자인', '프로그램', 'ACTIVE'),
    ('Sketch', '디자인', '프로그램', 'ACTIVE'),
    ('AdobeXD', '디자인', '프로그램', 'ACTIVE'),
    ('Illustrator', '디자인', '프로그램', 'ACTIVE'),
    ('Photoshop', '디자인', '프로그램', 'ACTIVE'),
    ('UI/UX', '디자인', '분야/직무', 'ACTIVE'),
    ('ProductDesign', '디자인', '분야/직무', 'ACTIVE'),
    ('그래픽디자인', '디자인', '분야/직무', 'ACTIVE'),
    ('브랜딩', '디자인', '분야/직무', 'ACTIVE'),
    ('InteractionDesign', '디자인', '분야/직무', 'ACTIVE'),
    ('디자인시스템', '디자인', '개념/이론', 'ACTIVE'),
    ('DesignThinking', '디자인', '개념/이론', 'ACTIVE'),
    ('프로토타이핑', '디자인', '개념/이론', 'ACTIVE'),
    ('와이어프레임', '디자인', '개념/이론', 'ACTIVE'),
    ('GUI', '디자인', '개념/이론', 'ACTIVE'),
    ('HTML/CSS', '디자인', '프론트 연관', 'ACTIVE'),
    ('반응형웹', '디자인', '프론트 연관', 'ACTIVE'),
    ('접근성', '디자인', '프론트 연관', 'ACTIVE'),
    ('모션그래픽', '디자인', '프론트 연관', 'ACTIVE'),
    ('웹표준', '디자인', '프론트 연관', 'ACTIVE'),
    ('디자인툴팁', '디자인', '기타', 'ACTIVE'),
    ('포트폴리오', '디자인', '기타', 'ACTIVE'),
    ('타이포그래피', '디자인', '기타', 'ACTIVE'),
    ('색상론', '디자인', '기타', 'ACTIVE'),
    ('사용성테스트', '디자인', '기타', 'ACTIVE'),
    ('프로덕트매니저', '서비스', '기획/전략', 'ACTIVE'),
    ('PM', '서비스', '기획/전략', 'ACTIVE'),
    ('서비스기획', '서비스', '기획/전략', 'ACTIVE'),
    ('MVP', '서비스', '기획/전략', 'ACTIVE'),
    ('비즈니스모델', '서비스', '기획/전략', 'ACTIVE'),
    ('Agile', '서비스', '애자일/협업', 'ACTIVE'),
    ('Scrum', '서비스', '애자일/협업', 'ACTIVE'),
    ('Jira', '서비스', '애자일/협업', 'ACTIVE'),
    ('노션', '서비스', '애자일/협업', 'ACTIVE'),
    ('팀워크', '서비스', '애자일/협업', 'ACTIVE'),
    ('그로스해킹', '서비스', '마케팅/운영', 'ACTIVE'),
    ('SEO', '서비스', '마케팅/운영', 'ACTIVE'),
    ('A/B테스트', '서비스', '마케팅/운영', 'ACTIVE'),
    ('데이터기반의사결정', '서비스', '마케팅/운영', 'ACTIVE'),
    ('CRM', '서비스', '마케팅/운영', 'ACTIVE'),
    ('스타트업', '서비스', '법률/경영', 'ACTIVE'),
    ('창업', '서비스', '법률/경영', 'ACTIVE'),
    ('IT법률', '서비스', '법률/경영', 'ACTIVE'),
    ('특허', '서비스', '법률/경영', 'ACTIVE'),
    ('투자', '서비스', '법률/경영', 'ACTIVE'),
    ('채용/면접', '서비스', '기타', 'ACTIVE'),
    ('개발문화', '서비스', '기타', 'ACTIVE'),
    ('커리어', '서비스', '기타', 'ACTIVE'),
    ('회고록', '서비스', '기타', 'ACTIVE'),
    ('외주/프리랜서', '서비스', '기타', 'ACTIVE')
    ON DUPLICATE KEY UPDATE
                         `category` = VALUES(`category`),
                         `sub_category` = VALUES(`sub_category`),
                         `status` = VALUES(`status`);

COMMIT;