### 내 정보 조회
GET http://localhost:8080/users/me
Content-Type: application/json

### 내 정보 조회 - 토큰 없음 (401)
GET http://localhost:8080/users/me
Content-Type: application/json

### 내 정보 수정
PATCH http://localhost:8080/users/me
Content-Type: application/json

{
  "name" : "update test",
  "tagIds": [1,2,5]
}
